version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports:
      - '3030:3000'
    volumes:
      - dependencies:/app/node_modules
      - .:/app
  db-redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
volumes:
  dependencies:
